--GRANT SELECT ON [viewname] TO [user]

--HPB\admTDennis
--HPB\TDennis


GRANT SELECT ON [vw_WMS_GP_Receipt_Compare] TO [HPB\admTDennis]
GRANT SELECT ON [vw_WMS_GP_Receipt_Compare] TO [HPB\TDennis]


GRANT SELECT ON [vw_WMS_GP_Shipment_Compare] TO [HPB\admTDennis]
GRANT SELECT ON [vw_WMS_GP_Shipment_Compare] TO [HPB\TDennis]

GRANT SELECT ON [vw_WMS_TTB_MinMax] TO [HPB\admTDennis]
GRANT SELECT ON [vw_WMS_TTB_MinMax] TO [HPB\TDennis]