Select 
'ALTER INDEX ALL ON ',TABLE_NAME,' REBUILD PARTITION = ALL 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, 
SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)'
FROM Information_schema.tables



/*
Generates Script Like:
(No column name)	TABLE_NAME	(No column name)
ALTER INDEX ALL ON 	App_LocationLabels	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_ChangeHistory_Archive	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Item_ChangeHistory_Archive	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_System_XMLImport	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Item_StatusCodes	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	App_GlobalVariables	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Comments	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_System_XMLExport	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_System_ExportTypes	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_ShipMethods	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_PostageMapping	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Customer	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_ChangeHistory	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_StatusCodes	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Error_StatusCodes	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Detail	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Error	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	App_GlobalSettings	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Batch_Processing	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Batch_StatusCodes	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Item_ChangeHistory	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Batch	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Header	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_ProblemStatus	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_Systems	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	App_LocationSettings	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	App_LocationVariables	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
ALTER INDEX ALL ON 	Order_System_XMLPaths	 REBUILD PARTITION = ALL   WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)

*/