grant select, update, insert, delete on blk.invoicedetail  to  [hpb\dist users]
grant select, update, insert, delete on blk.invoiceheader  to  [hpb\dist users]
grant select, update, insert, delete on blk.shipmentdetail  to  [hpb\dist users]
grant select, update, insert, delete on blk.shipmentheader  to  [hpb\dist users]
grant select, update, insert, delete on blk.purchaseorderdetail to  [hpb\dist users]
grant select, update, insert, delete on blk.purchaseorderheader to  [hpb\dist users]
grant select, update, insert, delete on blk.AcknowledgeDetail to [hpb\dist users]
grant select, update, insert, delete on blk.AcknowledgeHeader to  [hpb\dist users]

